# Generated by Django 4.1.4 on 2023-01-25 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lybrary', '0002_librarystudents_access_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LybraryOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('owner_date_of_birth', models.CharField(blank=True, max_length=10, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('owner_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('owner_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_city', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_lybrary_code', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
