# Generated by Django 4.1.4 on 2023-01-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lybrary', '0006_library_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lybraryowner',
            old_name='owner_lybrary_code',
            new_name='lybrary_code',
        ),
    ]
