# Generated by Django 4.1.4 on 2023-01-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lybrary', '0007_rename_owner_lybrary_code_lybraryowner_lybrary_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('lybrary', 'user_name')},
        ),
    ]
