# Generated by Django 4.1.4 on 2023-01-27 16:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lybrary', '0008_alter_student_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Library',
            new_name='Lybrary',
        ),
        migrations.RenameModel(
            old_name='LibraryStudents',
            new_name='LybraryStudents',
        ),
        migrations.RenameField(
            model_name='lybrary',
            old_name='library_code',
            new_name='lybrary_code',
        ),
        migrations.RenameField(
            model_name='lybrary',
            old_name='library_id',
            new_name='lybrary_id',
        ),
        migrations.RenameField(
            model_name='lybrary',
            old_name='library_name',
            new_name='lybrary_name',
        ),
        migrations.RenameField(
            model_name='lybrary',
            old_name='library_registration_number',
            new_name='lybrary_registration_number',
        ),
        migrations.RenameField(
            model_name='lybrarystudents',
            old_name='library_code',
            new_name='lybrary_code',
        ),
    ]
