# Generated by Django 4.1.4 on 2023-02-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lybrary", "0009_rename_library_lybrary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lybrarystudents",
            name="Father_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="Father_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
