# Generated by Django 3.1.1 on 2021-03-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_auto_20210320_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmaster',
            name='staff_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
