# Generated by Django 3.1.1 on 2021-03-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0053_staffmaster_staff_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
