# Generated by Django 3.1.1 on 2021-03-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_parents_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents_msg',
            name='sender_user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
