# Generated by Django 3.1.1 on 2021-08-17 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0059_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
