# Generated by Django 4.1.4 on 2022-12-16 17:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0060_profile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[640, 480], upload_to='images/'),
        ),
    ]
